### ISSUE TITLE
Answer design concept

### ISSUE THREAD

**Issue by ghost** [CalleyInc/statusbot#1]
Could you add embed answers to your bot? Like this. 
**It looks colorful and juicy :D**
![this](https://user-images.githubusercontent.com/52901647/66550678-5743ea80-eb5f-11e9-97bb-176edadbe442.png)

**Comment by Hadeslnc** [comment]
Nope XD

**Comment by Hadeslnc** [comment]
Cuz these embeds support markdown formatting, so any nicks with symbols
will be converted.

Although embeds support code insertions.

Also, Rist don't show off with English skills, at least not to me :D

**Comment by ghost** [comment]
Okay. I just used Google Translator :stuck_out_tongue_winking_eye:

**Comment by ghost** [comment]
Close this issue plz

**Comment by ghost** [comment]
Eh, I found a button to close this issue myself 😅
